{ config, pkgs, ... }:

{
  # Repositories
  nixpkgs.config.allowUnfree = true;
  nixpkgs.config.allowBroken = true;

  # Packages
  environment.systemPackages = with pkgs; [
    acpi
    adapta-gtk-theme
    aircrack-ng
    android-studio
    ansible
    ansible-lint
    ant
    apg
    arandr
    arp-scan
    asciinema
    aspell
    aspellDicts.en
    aspellDicts.fr
    audacity
    autoconf
    automake
    aws
    azure-cli
    baobab
    bash-completion
    bc
    binutils
    blobby
    brave
    bridge-utils
    cacert
    calibre
    chrome-gnome-shell
    chromium
    cmake
    containerd
    convmv
    coreutils
    cpufrequtils
    cryptsetup
    cups
    cups-filters
    curl
    ddrescue
    debootstrap
    diffutils
    # discord
    dmidecode
    dnsutils
    docker
    docker-compose
    dos2unix
    dosfstools
    dsniff
    e2fsprogs
    efitools
    efivar
    ethtool
    evince
    exfat
    exiftool
    expect
    ffmpeg
    file
    filezilla
    firefox-wayland
    flashrom
    freerdp
    fuseiso
    gcc
    geany
    ghidra-bin
    gimpPlugins.gmic
    gimp-with-plugins
    git-lfs
    glxinfo
    gmpc
    gnome3.dconf-editor
    gnome3.eog
    gnome3.gnome-characters
    gnome3.gnome-clocks
    gnome3.gnome-color-manager
    gnome3.gnome-disk-utility
    gnome3.gvfs
    gnome3.networkmanager-l2tp
    gnome3.networkmanager-openconnect
    gnome3.networkmanager-openvpn
    gnomeExtensions.appindicator
    gnomeExtensions.dash-to-panel
    gnomeExtensions.gsconnect
    gnomeExtensions.mpris-indicator-button
    gnomeExtensions.sound-output-device-chooser
    gnome-menus
    gnumake
    gnupg
    gnuplot
    go
    google-chrome
    google-cloud-sdk
    graphviz
    handbrake
    hexdump
    htop
    hugin
    hunspell
    hunspellDicts.en-us
    hunspellDicts.fr-any
    ifenslave
    iftop
    imagemagick
    inotify-tools
    iotop
    ipcalc
    jdk
    john
    jq
    keepassxc
    keychain
    krb5
    kubectl
    kubectx
    lftp
    libreoffice
    libvirt
    lm_sensors
    lshw
    lsof
    ltrace
    lvm2
    man
    man-pages
    meld
    mitmproxy
    mtpfs
    nix-bash-completions
    nix-index
    # nix-linter
    nix-zsh-completions
    nmap
    nodejs
    nox
    ntfs3g
    openvpn
    OVMF
    OVMF-secureBoot
    p7zip
    packer
    papirus-icon-theme
    parted
    pciutils
    pdfmod
    peek
    perl530Packages.AppClusterSSH
    posix_man_pages
    powertop
    procps
    psmisc
    python3Full
    pythonFull
    qemu_kvm
    qemu-utils
    rclone
    remmina
    rsync
    s3cmd
    s3fs
    screen
    shutter
    signal-desktop
    skypeforlinux
    slack
    smartmontools
    smplayer
    socat
    solaar
    sqlite
    sshfs
    ssldump
    ssss
    strace
    streamlink
    sysstat
    system-config-printer
    tcpdump
    tcpflow
    tdesktop
    teams
    telnet
    terraform
    terraform-providers.aws
    terraform-providers.azurerm
    terraform-providers.external
    terraform-providers.github
    terraform-providers.kubernetes
    terraform-providers.libvirt
    terraform-providers.local
    terraform-providers.null
    terraform-providers.vault
    testdisk
    tflint
    thunderbird
    tilix
    transmission-remote-gtk
    tsocks
    unrar
    unzip
    usbutils
    vim
    virt-manager
    vivaldi-ffmpeg-codecs
    vlc
    vscode-with-extensions
    wget
    which
    whois
    wine-staging
    winetricks
    wireshark
    yarn
    youtube-dl
    zip
    zoom-us
  ];

  imports = [
    ./32bits.nix
    ./avahi.nix
    ./boot.nix
    ./cron.nix
    ./cups.nix
    ./fail2ban.nix
    ./firefox.nix
    ./firewall.nix
    ./fonts.nix
    ./fwupd.nix
    ./gc.nix
    ./gcc.nix
    ./git.nix
    ./gnome
    ./localization.nix
    ./locate.nix
    ./openssh.nix
    ./polkit.nix
    ./python.nix
    ./shell.nix
    ./systemd.nix
    ./vim.nix
    ./vscode.nix
    ./udev.nix
    ./xresources.nix
    ./zfs.nix
  ];
}
